// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies
// @generated from protobuf file "clusters.proto" (package "pomerium.dashboard", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ClustersService } from "./clusters";
import type { UpdateClusterResponse } from "./clusters";
import type { UpdateClusterRequest } from "./clusters";
import type { ListClustersResponse } from "./clusters";
import type { ListClustersRequest } from "./clusters";
import type { GetClusterResponse } from "./clusters";
import type { GetClusterRequest } from "./clusters";
import type { DeleteClusterResponse } from "./clusters";
import type { DeleteClusterRequest } from "./clusters";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AddClusterResponse } from "./clusters";
import type { AddClusterRequest } from "./clusters";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service pomerium.dashboard.ClustersService
 */
export interface IClustersServiceClient {
    /**
     * @generated from protobuf rpc: AddCluster(pomerium.dashboard.AddClusterRequest) returns (pomerium.dashboard.AddClusterResponse);
     */
    addCluster(input: AddClusterRequest, options?: RpcOptions): UnaryCall<AddClusterRequest, AddClusterResponse>;
    /**
     * @generated from protobuf rpc: DeleteCluster(pomerium.dashboard.DeleteClusterRequest) returns (pomerium.dashboard.DeleteClusterResponse);
     */
    deleteCluster(input: DeleteClusterRequest, options?: RpcOptions): UnaryCall<DeleteClusterRequest, DeleteClusterResponse>;
    /**
     * @generated from protobuf rpc: GetCluster(pomerium.dashboard.GetClusterRequest) returns (pomerium.dashboard.GetClusterResponse);
     */
    getCluster(input: GetClusterRequest, options?: RpcOptions): UnaryCall<GetClusterRequest, GetClusterResponse>;
    /**
     * @generated from protobuf rpc: ListClusters(pomerium.dashboard.ListClustersRequest) returns (pomerium.dashboard.ListClustersResponse);
     */
    listClusters(input: ListClustersRequest, options?: RpcOptions): UnaryCall<ListClustersRequest, ListClustersResponse>;
    /**
     * @generated from protobuf rpc: UpdateCluster(pomerium.dashboard.UpdateClusterRequest) returns (pomerium.dashboard.UpdateClusterResponse);
     */
    updateCluster(input: UpdateClusterRequest, options?: RpcOptions): UnaryCall<UpdateClusterRequest, UpdateClusterResponse>;
}
/**
 * @generated from protobuf service pomerium.dashboard.ClustersService
 */
export class ClustersServiceClient implements IClustersServiceClient, ServiceInfo {
    typeName = ClustersService.typeName;
    methods = ClustersService.methods;
    options = ClustersService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddCluster(pomerium.dashboard.AddClusterRequest) returns (pomerium.dashboard.AddClusterResponse);
     */
    addCluster(input: AddClusterRequest, options?: RpcOptions): UnaryCall<AddClusterRequest, AddClusterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddClusterRequest, AddClusterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCluster(pomerium.dashboard.DeleteClusterRequest) returns (pomerium.dashboard.DeleteClusterResponse);
     */
    deleteCluster(input: DeleteClusterRequest, options?: RpcOptions): UnaryCall<DeleteClusterRequest, DeleteClusterResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteClusterRequest, DeleteClusterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCluster(pomerium.dashboard.GetClusterRequest) returns (pomerium.dashboard.GetClusterResponse);
     */
    getCluster(input: GetClusterRequest, options?: RpcOptions): UnaryCall<GetClusterRequest, GetClusterResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClusterRequest, GetClusterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListClusters(pomerium.dashboard.ListClustersRequest) returns (pomerium.dashboard.ListClustersResponse);
     */
    listClusters(input: ListClustersRequest, options?: RpcOptions): UnaryCall<ListClustersRequest, ListClustersResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListClustersRequest, ListClustersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCluster(pomerium.dashboard.UpdateClusterRequest) returns (pomerium.dashboard.UpdateClusterResponse);
     */
    updateCluster(input: UpdateClusterRequest, options?: RpcOptions): UnaryCall<UpdateClusterRequest, UpdateClusterResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateClusterRequest, UpdateClusterResponse>("unary", this._transport, method, opt, input);
    }
}
