#!/bin/bash
set -euo pipefail

_scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
_root_dir="$(dirname "$_scripts_dir")"
_deps_dir="$_root_dir/deps"

readonly _git_deps=(
    "pomerium/enterprise-client|6950db3e72cc20cceb172009941030cec8f18b9f"
    'envoyproxy/protoc-gen-validate|v1.2.1'
    'googleapis/googleapis|114a745b2841a044e98cdbb19358ed29fcf4a5f1'
)

function clone() {
    local _name="$1"
    local _tag="$2"
    local _dst="$3"

    echo "cloning $_name:$_tag to $_dst"
    if [ ! -d "$_dst" ]; then
        mkdir -p "$_dst"
        (cd "$_dst" && git init && git remote add origin "git@github.com:$_name")
    fi
    (
        cd "$_dst"
        git fetch --depth=1 origin
        git switch --force-create dev "$_tag"
    )
}

function clone-all() {
    local _name _tag _dst
    for _dep in "${_git_deps[@]}"; do
        IFS=$'|' read -r _name _tag <<<"$_dep"
        _dst="$_deps_dir/github.com/$_name"
        clone "$_name" "$_tag" "$_dst"
    done
}

clone-all

for _f in "$_deps_dir/github.com/pomerium/enterprise-client/protos/pomerium-console/"*.proto; do
    (
        cd "$(dirname "$_f")"
        mkdir -p "$_root_dir/src/pomerium-console"
        npx protoc \
            --ts_out="$_root_dir/src/pomerium-console" \
            --ts_opt="generate_dependencies" \
            --proto_path="$_deps_dir" \
            --proto_path="$_deps_dir/github.com/envoyproxy/protoc-gen-validate" \
            --proto_path="$_deps_dir/github.com/googleapis/googleapis" \
            --proto_path="$_deps_dir/github.com/pomerium/enterprise-client/protos/pomerium-console" \
            "$(basename "$_f")"
    )
done
